plugins {
    id 'com.android.application'
}

android {
    namespace 'com.chikaharu.firetvblelogger'
    compileSdk 35

    defaultConfig {
        applicationId "com.chikaharu.firetvblelogger"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }
}

dependencies {
}
